# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0004_auto_20160121_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='notes',
            field=models.CharField(max_length=300, null=True, verbose_name=b'Please enter descriptive notes about the sensor.'),
        ),
    ]
