# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0005_sensor_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='notes',
            field=models.CharField(default=b'No sensor notes available.', max_length=300, verbose_name=b'Please enter descriptive notes about the sensor.'),
        ),
    ]
