# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0006_auto_20160223_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='report_footer',
            field=models.TextField(blank=True, help_text=b'Use <a href="http://markdowntutorial.com/"> markdown syntax </a> to add links, pictures, etc.', verbose_name=b'Additional Building Documentation'),
        ),
    ]
