# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0010_periodicscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcondition',
            name='recipients',
            field=models.ManyToManyField(blank=True, to='bmsapp.AlertRecipient', verbose_name=b'Who should be notified?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='sensors',
            field=models.ManyToManyField(blank=True, through='bmsapp.BldgToSensor', to='bmsapp.Sensor'),
        ),
    ]
