# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0011_auto_20161028_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicscript',
            name='description',
            field=models.CharField(blank=True, max_length=80, verbose_name=b'Optional Description'),
        ),
    ]
