# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 20:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0013_periodicscript_hidden_script_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_id',
            field=models.CharField(max_length=80, unique=True, verbose_name=b'Sensor ID, or Calculated Field ID'),
        ),
    ]
