# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0014_auto_20161128_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarditem',
            name='widget_type',
            field=models.CharField(choices=[(b'gauge', b'Graph'), (b'LED', b'Red/Green LED'), (b'label', b'Label')], default=b'gauge', max_length=15),
        ),
    ]
