# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0016_building_timeline_annotations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarditem',
            name='widget_type',
            field=models.CharField(choices=[(b'graph', b'Graph'), (b'gauge', b'Gauge'), (b'LED', b'Red/Green LED'), (b'label', b'Label')], default=b'graph', max_length=15),
        ),
    ]
