# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0017_auto_20170315_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.IntegerField(default=999)),
                ('markdown_text', models.TextField(blank=True, help_text=b'Use <a href="http://markdowntutorial.com/">markdown syntax</a> to add links, pictures, etc.  Note that you <b>must</b> include the url prefix (e.g. <i>http://</i>) in any external links.', verbose_name=b'Report Content (in markdown):')),
            ],
            options={
                'ordering': ['group', 'sort_order', 'title'],
            },
        ),
    ]
