# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-01 19:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0022_auto_20170629_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcondition',
            name='alert_message',
            field=models.TextField(blank=True, help_text=b'If left blank, a message will be created automatically.', max_length=400),
        ),
    ]
