# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-30 03:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0023_auto_20170801_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcondition',
            name='read_count',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1 time'), (2, b'2 times'), (3, b'3 times'), (4, b'4 times'), (5, b'5 times')], default=1, verbose_name=b'Number of times Condition must occur before alerting'),
        ),
    ]
