# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-28 21:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0024_alertcondition_read_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.IntegerField(default=999)),
                ('building_groups', models.ManyToManyField(to='bmsapp.BuildingGroup')),
                ('buildings', models.ManyToManyField(to='bmsapp.Building')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
