# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0025_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='building_groups',
            field=models.ManyToManyField(blank=True, to='bmsapp.BuildingGroup'),
        ),
    ]
