# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0026_auto_20190328_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='custom_reports',
            field=models.ManyToManyField(blank=True, to='bmsapp.CustomReport'),
        ),
        migrations.AddField(
            model_name='organization',
            name='multi_charts',
            field=models.ManyToManyField(blank=True, to='bmsapp.MultiBuildingChart'),
        ),
    ]
