# Generated by Django 2.1.7 on 2019-09-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0030_auto_20190812_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bmsapp.Unit'),
        ),
    ]
