# Generated by Django 2.2.24 on 2021-10-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0033_alertcondition_only_if_bldg_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='notes_private',
            field=models.TextField(blank=True, help_text='Any text is valid and will only be seen by System Administrators.', verbose_name='Notes only seen by Sys Admins'),
        ),
    ]
