# Generated by Django 2.2.28 on 2023-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0035_auto_20230117_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcondition',
            name='last_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
