# Generated by Django 2.2.28 on 2024-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0037_auto_20230628_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecipientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('recipients', models.ManyToManyField(to='bmsapp.AlertRecipient')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='alertcondition',
            name='recipient_groups',
            field=models.ManyToManyField(blank=True, to='bmsapp.AlertRecipientGroup', verbose_name='Recipient Groups who should be notified'),
        ),
    ]
