# Generated by Django 2.2.28 on 2024-05-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0039_auto_20240313_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcondition',
            name='alert_timeout',
            field=models.FloatField(default=30.0, verbose_name='# of Days to Alert without a Sensor Reading Update'),
        ),
    ]
