# Generated by Django 2.2.28 on 2024-06-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0040_alertcondition_alert_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertcondition',
            name='read_count',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 time'), (2, '2 times'), (3, '3 times'), (4, '4 times'), (5, '5 times'), (10, '10 times'), (20, '20 times'), (30, '30 times'), (50, '50 times'), (75, '75 times'), (100, '100 times'), (150, '150 times'), (200, '200 times')], default=1, verbose_name='Number of times Condition must occur before alerting'),
        ),
    ]
