# Generated by Django 2.2.28 on 2025-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsapp', '0041_auto_20240627_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrecipient',
            name='notify_pushover',
            field=models.BooleanField(default=False, verbose_name='Send Pushover Notification?'),
        ),
    ]
