"""
This module contains dictionaries of formatting codes used by formatters.py
"""

# Okofen Pellet Boiler status codes
okofen_status_codes = {
 0: 'Standby',
 1: 'Ignition 1',
 2: 'Ignition 2',
 3: 'Ignition 3',
 4: 'Ignition 4',
 5: 'Ignited/Burning',
 6: 'Shutdown/Burnout Process',
 7: 'Ash Vac Cleanout',
}

aerco_fault_code_bitmask_dictionary = \
    {0: 'Outside Air Sensor Error',
     1: 'Header Sensor Error',
     2: 'Interlock 1 Error',
     3: 'Interlock 2 Error',
     4: 'Indoor/Return Air Sensor Error',
     5: '4-20mA Input Error'}

aerco_io_status_bitmask_dictionary = \
    {0: 'AUX Relay',
     1: 'Fault Relay',
     2: 'Sys Start Relay',
     4: 'Setback',
     5: 'Interlock 2',
     6: 'Interlock 1'}

aerco_boiler_status_dictionary = \
    {119: 'Not On-Line',
     120: 'On-Line But Not Fired',
     121: 'On-Line But Disabled',
     122: 'On-Line But Faulted'}

sage_limits_bitmask_dictionary = \
    {0: 'Outlet high limit',
     1: 'DHW high limit',
     2: 'Stack limit',
     3: 'Delta T inlet/outlet limit',
     4: 'Delta T exchanger/outlet limit',
     5: 'Delta T inlet/exchanger limit',
     6: 'Inversion inlet/outlet limit',
     7: 'Inversion exchanger/outlet limit',
     8: 'Inversion inlet/exchanger limit',
     9: 'Outlet T-rise limit',
     10: 'Exchanger T-rise limit',
     11: 'Heat exchanger high limit'}

sage_alarm_reason_dictionary = \
    {0: 'None',
     1: 'Lockout (see Lockout Code)',
     2: 'Alert (see Table 11)',
     3: 'Other'}

sage_demand_source_dictionary = \
    {0: 'Unknown',
     1: 'No source demand',
     2: 'Space Ht',
     3: 'DHW',
     4: 'Lead Lag slave',
     5: 'Lead Lag master',
     6: 'Space Ht frost protection',
     7: 'DHW frost protection',
     8: 'No demand (burner switch turned off)',
     9: 'DHW storage',
     10: 'Reserved',
     11: 'Warm weather shutdown'}

sage_lockout_code_dictionary = \
    {0: 'None',
     1: 'Unconfigured safety data',
     2: 'Waiting for safety data verification',
     3: 'Internal fault: Hardware fault',
     4: 'Internal fault: Safety Relay key feedback error',
     5: 'Internal fault: Unstable power (DCDC) output',
     6: 'Internal fault: Invalid processor clock',
     7: 'Internal fault: Safety relay drive error',
     8: 'Internal fault: Zero crossing not detected',
     9: 'Internal fault: Flame bias out of range',
     10: 'Internal fault: Invalid Burner control state',
     11: 'Internal fault: Invalid Burner control state flag',
     12: 'Internal fault: Safety relay drive cap short',
     13: 'Internal fault: PII shorted to ILK',
     14: 'Internal fault: HFS shorted to LCI',
     15: 'Internal fault: Safety relay test failed due to feedback ON',
     16: 'Internal fault: Safety relay test failed dueto safety relay OFF',
     17: 'Internal fault: Safety relay test failed due to safety relay not OFF',
     18: 'Internal fault: Safety relay test failed due to feedback not ON',
     19: 'Internal fault: Safety RAM write',
     20: 'Internal fault: Flame ripple and overflow',
     21: 'Internal fault: Flame number of sample mismatch',
     22: 'Internal fault: Flame bias out of range',
     23: 'Internal fault: Bias changed since heating cycle starts',
     24: 'Internal fault: Spark voltage stuck low or high',
     25: 'Internal fault: Spark voltage changed too much during flame sensing time',
     26: 'Internal fault: Static flame ripple',
     27: 'Internal fault: Flame rod shorted to ground detected',
     28: 'Internal fault: A/D linearity test fails',
     29: 'Internal fault: Flame bias cannot be set in range',
     30: 'Internal fault: Flame bias shorted to adjacent pin',
     31: 'Internal fault: SLO electronics unknown error',
     32: 'Internal fault: Safety Key 0',
     33: 'Internal fault: Safety Key 1',
     34: 'Internal fault: Safety Key 2',
     35: 'Internal fault: Safety Key 3',
     36: 'Internal fault: Safety Key 4',
     37: 'Internal fault: Safety Key 5',
     38: 'Internal fault: Safety Key 6',
     39: 'Internal fault: Safety Key 7',
     40: 'Internal fault: Safety Key 8',
     41: 'Internal fault: Safety Key 9',
     42: 'Internal fault: Safety Key 10',
     43: 'Internal fault: Safety Key 11',
     44: 'Internal fault: Safety Key 12',
     45: 'Internal fault: Safety Key 13',
     46: 'Internal fault: Safety Key 14',
     47: 'Flame rod to ground leakage',
     48: 'Static flame (not flickering)',
     49: '24VAC voltage low/high',
     50: 'Modulation fault',
     51: 'Pump fault',
     52: 'Motor tachometer fault',
     53: 'AC inputs phase reversed',
     54: 'Safety GVT model ID doesn\'t match application\'s model ID',
     55: 'Application configuration data block CRC errors',
     58: 'Internal fault: HFS shorted to IAS',
     59: 'Internal fault: Mux pin shorted',
     60: 'Internal fault: HFS shorted to LFS',
     61: 'Anti short cycle',
     62: 'Fan speed not proved',
     63: 'LCI OFF',
     64: 'PII OFF',
     65: 'Interrupted Airflow Switch OFF',
     66: 'Interrupted Airflow Switch ON',
     67: 'ILK OFF',
     68: 'ILK ON',
     69: 'Pilot test hold',
     70: 'Wait for leakage test completion',
     71: 'Input power frequency mismatch',
     78: 'Demand lost in run',
     79: 'Outlet high limit',
     80: 'DHW high limit',
     81: 'Delta T inlet/outlet limit',
     82: 'Stack limit',
     83: 'Delta T exchanger/outlet limit',
     84: 'Delta T inlet/exchanger limit',
     85: 'Inlet/outlet inversion limit',
     86: 'Exchanger/outlet inversion limit',
     87: 'Inlet/exchanger inversion limit',
     88: 'Outlet T-rise limit',
     89: 'Exchanger T-rise limit',
     90: 'Heat exchanger high limit',
     91: 'Inlet sensor fault',
     92: 'Outlet sensor fault',
     93: 'DHW sensor fault',
     94: 'S2 (J8-6) sensor fault',
     95: 'Stack sensor fault',
     96: 'S5 (J8-11) sensor fault',
     97: 'Internal fault: A2D mismatch',
     98: 'Internal fault: Exceeded VSNSR voltage tolerance',
     99: 'Internal fault: Exceeded 28V voltage tolerance',
     100: 'Pressure sensor fault',
     105: 'Flame detected out of sequence',
     106: 'Flame lost in MFEP',
     107: 'Flame lost early in run',
     108: 'Flame lost in run',
     109: 'Ignition failed',
     110: 'Ignition failure occurred',
     111: 'Flame current lower than WEAK threshold',
     112: 'Pilot test flame timeout',
     113: 'Flame circuit timeout',
     122: 'Lightoff rate proving failed',
     123: 'Purge rate proving failed',
     124: 'High fire switch OFF',
     125: 'High fire switch stuck ON',
     126: 'Low fire switch OFF',
     127: 'Low fire switch stuck ON',
     128: 'Fan speed failed during prepurge',
     129: 'Fan speed failed during preignition',
     130: 'Fan speed failed during ignition',
     131: 'Fan movement detected during standby',
     132: 'Fan speed failed during run',
     136: 'Interrupted Airflow Switch failed to close',
     137: 'ILK failed to close',
     143: 'Internal fault: Flame bias out of range 1',
     144: 'Internal fault: Flame bias out of range 2',
     145: 'Internal fault: Flame bias out of range 3',
     146: 'Internal fault: Flame bias out of range 4',
     147: 'Internal fault: Flame bias out of range 5',
     148: 'Internal fault: Flame bias out of range 6',
     149: 'Flame detected',
     150: 'Flame not detected',
     151: 'High fire switch ON',
     152: 'Combustion pressure ON',
     153: 'Combustion pressure OFF',
     154: 'Purge fan switch ON',
     155: 'Purge fan switch OFF',
     156: 'Combustion pressure and Flame ON',
     157: 'Combustion pressure and Flame OFF',
     158: 'Main valve ON',
     159: 'Main valve OFF',
     160: 'Ignition ON',
     161: 'Ignition OFF',
     162: 'Pilot valve ON',
     163: 'Pilot valve OFF',
     164: 'Block intake ON',
     165: 'Block intake OFF',
     172: 'Main relay feedback incorrect',
     173: 'Pilot relay feedback incorrect',
     174: 'Safety relay feedback incorrect',
     175: 'Safety relay open',
     176: 'Main relay ON at safe start check',
     177: 'Pilot relay ON at safe start check',
     178: 'Safety relay ON at safe start check',
     184: 'Invalid BLOWER/HSI output setting',
     185: 'Invalid Delta T limit enable setting',
     186: 'Invalid Delta T limit response setting',
     187: 'Invalid DHW high limit enable setting',
     188: 'Invalid DHW high limit response setting',
     189: 'Invalid Flame sensor type setting',
     190: 'Invalid interrupted air switch enable setting',
     191: 'Invalid interrupted air switch start check enable setting',
     192: 'Invalid Igniter on during setting',
     193: 'Invalid Ignite failure delay setting',
     194: 'Invalid Ignite failure response setting',
     195: 'Invalid Ignite failure retries setting',
     196: 'Invalid Ignition source setting',
     197: 'Invalid Interlock open response setting',
     198: 'Invalid Interlock start check setting',
     199: 'Invalid LCI enable setting',
     200: 'Invalid lightoff rate setting',
     201: 'Invalid Lightoff rate proving setting',
     202: 'Invalid Main Flame Establishing Period time setting',
     203: 'Invalid MFEP flame failure response setting',
     204: 'Invalid NTC sensor type setting',
     205: 'Invalid Outlet high limit response setting',
     206: 'Invalid Pilot Flame Establishing Period setting',
     207: 'Invalid PII enable setting',
     208: 'Invalid pilot test hold setting',
     209: 'Invalid Pilot type setting',
     210: 'Invalid Postpurge time setting',
     211: 'Invalid Power up with lockout setting',
     212: 'Invalid Preignition time setting',
     213: 'Invalid Prepurge rate setting',
     214: 'Invalid Prepurge time setting',
     215: 'Invalid Purge rate proving setting',
     216: 'Invalid Run flame failure response setting',
     217: 'Invalid Run stabilization time setting',
     218: 'Invalid Stack limit enable setting',
     219: 'Invalid Stack limit response setting',
     220: 'Unconfigured Delta T limit setpoint setting',
     221: 'Unconfigured DHW high limit setpoint setting',
     222: 'Unconfigured Outlet high limit setpoint setting',
     223: 'Unconfigured Stack limit setpoint setting',
     224: 'Invalid DHW demand source setting',
     225: 'Invalid Flame threshold setting',
     226: 'Invalid Outlet high limit setpoint setting',
     227: 'Invalid DHW high limit setpoint setting',
     228: 'Invalid Stack limit setpoint setting',
     229: 'Invalid Modulation output setting',
     230: 'Invalid CH demand source setting',
     231: 'Invalid Delta T limit delay setting',
     232: 'Invalid Pressure sensor type setting',
     233: 'Invalid IAS closed response setting',
     234: 'Invalid Outlet high limit enable setting',
     235: 'Invalid Outlet connector type setting',
     236: 'Invalid Inlet connector type setting',
     237: 'Invalid DHW connector type setting',
     238: 'Invalid Stack connector type setting',
     239: 'Invalid S2 (J8-6) connector type setting',
     240: 'Invalid S5 (J8-11) connector type setting',
     241: 'Exchanger sensor not allowed with stack connector setting',
     242: 'Invalid DHW auto detect configuration',
     243: 'Invalid UV with spark interference not compatible with Ignitor on throughout PFEP',
     244: 'Internal fault: Safety relay test invalid state',
     245: 'Invalid Outlet connector type setting for T- rise',
     246: '4-20mA cannot be used for both modulation and setpoint control',
     247: 'Invalid ILK bounce detection enable',
     248: 'Invalid forced recycle interval',
     249: 'STAT cannot be demand source when Remote Stat is enabled',
     250: 'Invalid Fan speed error response',
     251: 'Lead drop-stage on error setting does not match drop method configuration',
     252: 'Invalid Line frequency setting'}

sage_alert_code_dictionary = \
    {0: 'None',
     1: 'Alert PCB was restored from factory defaults',
     2: 'Safety configuration parameters were restored from factory defaults',
     3: 'Configuration parameters were restored from factory defaults',
     4: 'Invalid Factory Invisibility PCB was detected',
     5: 'Invalid Factory Range PCB was detected',
     6: 'Invalid range PCB record has been dropped',
     7: 'EEPROM lockout history was initialized',
     8: 'Switched application annunciation data blocks',
     9: 'Switched application configuration data blocks',
     10: 'Configuration was restored from factory defaults',
     11: 'Backup configuration settings was restored from active configuration',
     12: 'Annunciation configuration was restored from factory defaults',
     13: 'Annunciation configuration was restored from backup',
     14: 'Safety group verification table was restored from factory defaults',
     15: 'Safety group verification table was updated',
     16: 'Invalid Parameter PCB was detected',
     17: 'Invalid Range PCB was detected',
     18: 'Alarm silence time exceeded maximum',
     19: 'Invalid safety group verification table was detected',
     20: 'Backdoor password could not be determined',
     21: 'Invalid safety group verification table was not accepted',
     22: 'CRC errors were found in application configuration data blocks',
     23: 'Backup Alert PCB was restored from active one',
     25: 'Lead Lag operation switch was turned OFF',
     26: 'Lead Lag operation switch was turned ON',
     27: 'Safety processor was reset',
     28: 'Application processor was reset',
     29: 'Burner switch was turned OFF',
     30: 'Burner switch was turned ON',
     31: 'Program Module (PM) was inserted into socket',
     32: 'Program Module (PM) was removed from socket',
     33: 'Alert PCB was configured',
     34: 'Parameter PCB was configured',
     35: 'Range PCB was configured',
     36: 'Program Module (PM) incompatible with product was inserted into socket',
     37: 'Program Module application parameter revision differs from application processor',
     38: 'Program Module safety parameter revision differs from safety processor',
     39: 'PCB incompatible with product contained in Program Module',
     40: 'Parameter PCB in Program Module is too large for product',
     41: 'Range PCB in Program Module was too large for product',
     42: 'Alert PCB in Program Module was too large for product',
     43: 'IAS start check was forced on due to IAS enabled',
     44: 'Low voltage was detected in safety processor',
     45: 'High line frequency occurred',
     46: 'Low line frequency occurred',
     47: 'Invalid subsystem reset request occurred',
     48: 'Write large enumerated Modbus register value was, not allowed',
     49: 'Maximum cycle count was reached',
     50: 'Maximum hours count was reached',
     51: 'Illegal Modbus write was attempted',
     52: 'Modbus write attempt was rejected (NOT ALLOWED)',
     53: 'Illegal Modbus read was attempted',
     54: 'Safety processor brown-out reset occurred',
     55: 'Application processor watchdog reset occurred',
     56: 'Application processor brown-out reset occurred',
     57: 'Safety processor watchdog reset occurred',
     58: 'Alarm was reset by the user at the control',
     59: 'Burner control firing rate was > absolute max rate',
     60: 'Burner control firing rate was < absolute min rate',
     61: 'Burner control firing rate was invalid, % vs. RPM',
     62: 'Burner control was firing with no fan request',
     63: 'Burner control rate (nonfiring) was > absolute max rate',
     64: 'Burner control rate (nonfiring) was < absolute min rate',
     65: 'Burner control rate (nonfiring) was absent',
     66: 'Burner control rate (nonfiring) was invalid, % vs. RPM',
     67: 'Fan off cycle rate was invalid, % vs. RPM',
     68: 'Setpoint was overridden due to sensor fault',
     69: 'Modulation was overridden due to sensor fault',
     70: 'No demand source was set due to demand priority conflicts',
     71: 'CH 4-20mA signal was invalid',
     74: 'Periodic Forced Recycle',
     75: 'Absolute max fan speed was out of range',
     76: 'Absolute min fan speed was out of range',
     77: 'Fan gain down was invalid',
     78: 'Fan gain up was invalid',
     79: 'Fan minimum duty cycle was invalid',
     80: 'Fan pulses per revolution was invalid',
     81: 'Fan PWM frequency was invalid',
     84: 'Lead Lag CH 4-20mA water temperature setting was invalid',
     85: 'No Lead Lag add stage error threshold was configured',
     86: 'No Lead Lag add stage detection time was configured',
     87: 'No Lead Lag drop stage error threshold was configured',
     88: 'No Lead Lag drop stage detection time was configured',
     89: 'Lead Lag all boiler off threshold was invalid',
     90: 'Modulation output type was invalid',
     91: 'Firing rate control parameter was invalid',
     92: 'Forced rate was out of range vs. min/max modulation',
     93: 'Forced rate was invalid, % vs. RPM',
     94: 'Slow start ramp value was invalid',
     95: 'Slow start degrees value was invalid',
     96: 'Slow start was ended due to outlet sensor fault',
     97: 'Slow start was end due to reference setpoint fault',
     98: 'CH max modulation rate was invalid, % vs. RPM',
     99: 'CH max modulation rate was > absolute max rate',
     100: 'CH modulation range (max minus min) was too small (< 4% or 40 RPM)',
     101: 'DHW max modulation rate was invalid, % vs. RPM',
     102: 'DHW max modulation rate was > absolute max rate',
     103: 'DHW modulation range (max minus min) was too small (< 4% or 40 RPM)',
     104: 'Min modulation rate was < absolute min rate',
     105: 'Min modulation rate was invalid, % vs. RPM',
     106: 'Manual rate was invalid, % vs. RPM',
     107: 'Slow start enabled, but forced rate was invalid',
     108: 'Analog output hysteresis was invalid',
     109: 'Analog modulation output type was invalid',
     110: 'IAS open rate differential was invalid',
     111: 'IAS open step rate was invalid',
     112: 'Mix max modulation rate was invalid, % vs. RPM',
     113: 'Mix max modulation rate was > absolute max or < absolute min rates',
     114: 'Mix modulation range (max minus min) was too small (< 4% or 40 RPM)',
     115: 'Fan was limited to its minimum duty cycle',
     116: 'Manual rate was > CH max modulation rate',
     117: 'Manual rate was > DHW max modulation rate',
     118: 'Manual rate was < min modulation rate',
     119: 'Manual rate in Standby was > absolute max rate',
     120: 'Modulation commanded rate was > CH max modulation rate',
     121: 'Modulation commanded rate was > DHW max modulation rate',
     122: 'Modulation commanded rate was < min modulation rate',
     123: 'Modulation rate was limited due to Outlet limit',
     124: 'Modulation rate was limited due to Delta-T limit',
     125: 'Modulation rate was limited due to Stack limit',
     126: 'Modulation rate was limited due to anticondensation',
     127: 'Fan speed out of range in RUN',
     128: 'Modulation rate was limited due to IAS was open',
     129: 'Slow start ramp setting of zero will result in no modulation rate change',
     130: 'No forced rate was configured for slow start ramp',
     131: 'CH demand source was invalid',
     132: 'CH P-gain was invalid',
     133: 'CH I-gain was invalid',
     134: 'CH D-gain was invalid',
     135: 'CH OFF hysteresis was invalid',
     136: 'CH ON hysteresis was invalid',
     137: 'CH sensor type was invalid',
     138: 'CH hysteresis step time was invalid',
     139: 'CH remote control parameter was invalid',
     140: 'CH ODR not allowed with remote control',
     141: 'Steam P-gain was invalid',
     142: 'Steam I-gain was invalid',
     143: 'Steam D-gain was invalid',
     144: 'Steam OFF hysteresis was invalid',
     145: 'Steam ON hysteresis was invalid',
     146: 'CH control was suspended due to fault',
     147: 'CH header temperature was invalid',
     148: 'CH Outlet temperature was invalid',
     149: 'CH steam pressure was invalid',
     150: 'Steam setpoint source parameter was invalid',
     151: 'Minimum water temperature parameter was greater than setpoint',
     152: 'Minimum water temperature parameter was greater than time of day setpoint',
     153: 'Minimum pressure parameter was greater than setpoint',
     154: 'Minimum pressure parameter was greater than time of day setpoint',
     155: 'CH modulation rate source parameter was invalid',
     156: 'Steam modulation rate source parameter was invalid',
     157: 'DHW demand source was invalid',
     158: 'DHW P-gain was invalid',
     159: 'DHW I-gain was invalid',
     160: 'DHW D-gain was invalid',
     161: 'DHW OFF hysteresis was invalid',
     162: 'DHW ON hysteresis was invalid',
     163: 'DHW hysteresis step time was invalid',
     164: 'DHW sensor type was invalid',
     165: 'Inlet sensor type was invalid for DHW',
     166: 'Outlet sensor type was invalid for DHW',
     167: 'DHW storage OFF hysteresis was invalid',
     168: 'DHW storage ON hysteresis was invalid',
     169: 'DHW modulation sensor type was invalid',
     170: 'DHW modulation sensor was not compatible for Auto mode',
     171: 'DHW control was suspended due to fault',
     172: 'DHW temperature was invalid',
     173: 'DHW inlet temperature was invalid',
     174: 'DHW outlet temperature was invalid',
     175: 'DHW high limit must be disabled for Auto mode',
     176: 'DHW sensor type was not compatible for Auto mode',
     177: 'DHW priority source setting was invalid',
     178: 'DHW priority method setting was invalid',
     179: 'CH S5 (J8-11) sensor was invalid',
     180: 'CH Inlet temperature was invalid',
     181: 'CH S10 (J10-7) sensor was invalid',
     182: 'Lead Lag CH setpoint source was invalid',
     183: 'Lead Lag P-gain was invalid',
     184: 'Lead Lag I-gain was invalid',
     185: 'Lead Lag D-gain was invalid',
     186: 'Lead Lag OFF hysteresis was invalid',
     187: 'Lead Lag ON hysteresis was invalid',
     188: 'Lead Lag slave enable was invalid',
     189: 'Lead Lag hysteresis step time was invalid',
     190: 'No Lead Lag Modbus port was assigned',
     191: 'Lead Lag base load common setting was invalid',
     192: 'Lead Lag DHW demand switch setting was invalid',
     193: 'Lead Lag Mix demand switch setting was invalid',
     194: 'Lead Lag modulation sensor setting was invalid',
     195: 'Lead Lag backup modulation sensor setting was invalid',
     196: 'Lead Lag slave mode setting was invalid',
     197: 'Lead Lag rate allocation setting was invalid',
     198: 'Lead selection setting was invalid',
     199: 'Lag selection setting was invalid',
     200: 'Lead Lag slave return setting was invalid',
     201: 'Lead Lag add stage method setting was invalid',
     202: 'STAT may not be a Lead Lag CH demand source when Remote Stat is enabled',
     203: 'Lead Lag base load rate setting was invalid',
     204: 'Lead Lag master was suspended due to fault',
     205: 'Lead Lag slave was suspended due to fault',
     206: 'Lead Lag header temperature was invalid',
     207: 'Lead Lag was suspended due to no enabled Program Module installed',
     208: 'Lead Lag slave session has timed out',
     209: 'Too many Lead Lag slaves were detected',
     210: 'Lead Lag slave was discovered',
     211: 'Incompatible Lead Lag slave was discovered',
     212: 'No base load rate was set for Lead Lag slave',
     213: 'Lead Lag slave unable to fire before demand to fire delay expired',
     214: 'Adding Lead Lag slave aborted due to add requirement change',
     215: 'No Lead Lag slaves available to service demand',
     216: 'No Lead Lag active service was set due to demand priority conflicts',
     217: 'No Lead Lag add stage method was specified',
     218: 'No Lead Lag drop stage method was specified',
     219: 'Using backup Lead Lag header sensor due to sensor failure',
     220: 'Lead Lag frost protection rate was invalid',
     221: 'Lead Lag drop stage method setting was invalid',
     222: 'CH frost protection temperature was invalid',
     223: 'CH frost protection inlet temperature was invalid',
     224: 'DHW frost protection temperature was invalid',
     227: 'DHW priority override time was not derated due to invalid outdoor temperature',
     228: 'Warm weather shutdown was not checked due to invalid outdoor temperature',
     229: 'Lead Lag slave communication timeout',
     231: 'Lead Lag CH setpoint was invalid',
     232: 'Lead Lag CH time of day setpoint was invalid',
     233: 'Lead Lag outdoor temperature was invalid',
     234: 'Lead Lag ODR time of day setpoint was invalid',
     235: 'Lead Lag ODR time of day setpoint exceeded normal setpoint',
     236: 'Lead Lag ODR max outdoor temperature was invalid',
     237: 'Lead Lag ODR min outdoor temperature was invalid',
     238: 'Lead Lag ODR low water temperature was invalid',
     239: 'Lead Lag ODR outdoor temperature range was too small (minimum 12 C / 22 F)',
     240: 'Lead Lag ODR water temperature range was too small (minimum 12 C / 22 F)',
     241: 'Lead Lag DHW setpoint was invalid',
     242: 'Lead Lag Mix setpoint was invalid',
     243: 'Lead Lag CH demand switch was invalid',
     244: 'Lead Lag ODR min water temperature was invalid',
     246: 'CH setpoint was invalid',
     247: 'CH time of day setpoint was invalid',
     248: 'CH outdoor temperature was invalid',
     249: 'CH ODR time of day setpoint was invalid',
     250: 'CH ODR time of day setpoint exceeds normal setpoint',
     251: 'CH max outdoor setpoint was invalid',
     252: 'CH min outdoor setpoint was invalid',
     253: 'CH ODR low water temperature was invalid',
     254: 'CH ODR outdoor temperature range was too small',
     255: 'CH ODR water temperature range was too small',
     256: 'Steam setpoint was invalid',
     257: 'Steam time of day setpoint was invalid',
     258: 'Steam minimum pressure was invalid',
     259: 'CH ODR min water temperature was invalid',
     261: 'DHW setpoint was invalid',
     262: 'DHW time of day setpoint was invalid',
     263: 'DHW storage setpoint was invalid',
     264: 'STAT may not be a DHW demand source when Remote Stat is enabled',
     267: 'STAT may not be a CH demand source when Remote Stat is enabled',
     268: 'CH 4mA water temperature setting was invalid',
     269: 'CH 20mA water temperature setting was invalid',
     270: 'Steam 4mA water temperature setting was invalid',
     271: 'Steam 20mA water temperature setting was invalid',
     272: 'Abnormal Recycle: Pressure sensor fault',
     273: 'Abnormal Recycle: Safety relay drive test failed',
     274: 'Abnormal Recycle: Demand off during Pilot Flame Establishing Period',
     275: 'Abnormal Recycle: LCI off during Drive to Purge Rate',
     276: 'Abnormal Recycle: LCI off during Measured Purge Time',
     277: 'Abnormal Recycle: LCI off during Drive to Lightoff Rate',
     278: 'Abnormal Recycle: LCI off during Pre-Ignition test',
     279: 'Abnormal Recycle: LCI off during Pre-Ignition time',
     280: 'Abnormal Recycle: LCI off during Main Flame Establishing Period',
     281: 'Abnormal Recycle: LCI off during Ignition period',
     282: 'Abnormal Recycle: Demand off during Drive to Purge Rate',
     283: 'Abnormal Recycle: Demand off during Measured Purge Time',
     284: 'Abnormal Recycle: Demand off during Drive to Lightoff Rate',
     285: 'Abnormal Recycle: Demand off during Pre-Ignition test',
     286: 'Abnormal Recycle: Demand off during Pre-Ignition time',
     287: 'Abnormal Recycle: Flame was on during Safe Start check',
     288: 'Abnormal Recycle: Flame was on during Drive to Purge Rate',
     289: 'Abnormal Recycle: Flame was on during Measured Purge Time',
     290: 'Abnormal Recycle: Flame was on during Drive to Lightoff Rate',
     291: 'Abnormal Recycle: Flame was not on at end of Ignition period',
     292: 'Abnormal Recycle: Flame was lost during Main Flame Establishing Period',
     293: 'Abnormal Recycle: Flame was lost early in Run',
     294: 'Abnormal Recycle: Flame was lost during Run',
     295: 'Abnormal Recycle: Leakage test failed',
     296: 'Abnormal Recycle: Interrupted air flow switch was off during Drive to Purge Rate',
     297: 'Abnormal Recycle: Interrupted air flow switch was off during Measured Purge Time',
     298: 'Abnormal Recycle: Interrupted air flow switch was off during Drive to Lightoff Rate',
     299: 'Abnormal Recycle: Interrupted air flow switch was off during Pre-Ignition test',
     300: 'Abnormal Recycle: Interrupted air flow switch was off during Pre-Ignition time',
     301: 'Abnormal Recycle: Interrupted air flow switch was off during Main Flame Establishing Period',
     302: 'Abnormal Recycle: Ignition failed due to interrupted air flow switch was off',
     303: 'Abnormal Recycle: ILK off during Drive to Purge Rate',
     304: 'Abnormal Recycle: ILK off during Measured Purge Time',
     305: 'Abnormal Recycle: ILK off during Drive to Lightoff Rate',
     306: 'Abnormal Recycle: ILK off during Pre-Ignition test',
     307: 'Abnormal Recycle: ILK off during Pre-Ignition time',
     308: 'Abnormal Recycle: ILK off during Main Flame Establishing Period',
     309: 'Abnormal Recycle: ILK off during Ignition period',
     310: 'Run was terminated due to ILK was off',
     311: 'Run was terminated due to interrupted air flow switch was off',
     312: 'Stuck reset switch',
     313: 'Run was terminated due to fan failure',
     314: 'Abnormal Recycle: Fan failed during Drive to Purge Rate',
     315: 'Abnormal Recycle: Fan failed during Measured Purge Time',
     316: 'Abnormal Recycle: Fan failed during Drive to Lightoff Rate',
     317: 'Abnormal Recycle: Fan failed during Pre-Ignition test',
     318: 'Abnormal Recycle: Fan failed during Pre-Ignition time',
     319: 'Abnormal Recycle: Fan failed during Ignition period',
     320: 'Abnormal Recycle: Fan failed during Main Flame Establishing Period',
     321: 'Abnormal Recycle: Main Valve off after 10 seconds of RUN',
     322: 'Abnormal Recycle: Pilot Valve off after 10 seconds of RUN',
     323: 'Abnormal Recycle: Safety Relay off after 10 seconds of RUN',
     324: 'Abnormal Recycle: Hardware flame bias',
     325: 'Abnormal Recycle: Hardware static flame',
     326: 'Abnormal Recycle: Hardware flame current invalid',
     327: 'Abnormal Recycle: Hardware flame rod short',
     328: 'Abnormal Recycle: Hardware invalid power',
     329: 'Abnormal Recycle: Hardware invalid AC line',
     330: 'Abnormal Recycle: Hardware SLO flame ripple',
     331: 'Abnormal Recycle: Hardware SLO flame sample',
     332: 'Abnormal Recycle: Hardware SLO flame bias range',
     333: 'Abnormal Recycle: Hardware SLO flame bias heat',
     334: 'Abnormal Recycle: Hardware SLO spark stuck',
     335: 'Abnormal Recycle: Hardware SLO spark changed',
     336: 'Abnormal Recycle: Hardware SLO static flame',
     337: 'Abnormal Recycle: Hardware SLO rod shorted',
     338: 'Abnormal Recycle: Hardware SLO AD linearity',
     339: 'Abnormal Recycle: Hardware SLO bias not set',
     340: 'Abnormal Recycle: Hardware SLO bias shorted',
     341: 'Abnormal Recycle: Hardware SLO electronics',
     342: 'Abnormal Recycle: Hardware processor clock',
     343: 'Abnormal Recycle: Hardware AC phase',
     344: 'Abnormal Recycle: Hardware A2D mismatch',
     345: 'Abnormal Recycle: Hardware VSNSR A2D',
     346: 'Abnormal Recycle: Hardware 28V A2D',
     347: 'Abnormal Recycle: Hardware HFS IAS shorted',
     348: 'Abnormal Recycle: Hardware PII INTLK shorted',
     349: 'Abnormal Recycle: Hardware HFS LCI shorted',
     350: 'Abnormal Recycle: Hardware HFS LFS shorted',
     351: 'Abnormal Recycle: Invalid zero crossing',
     352: 'Abnormal Recycle: fault stack sensor',
     353: 'Abnormal Recycle: stack limit',
     354: 'Abnormal Recycle: delta T limit',
     355: 'Abnormal Recycle: fault outlet sensor',
     356: 'Abnormal Recycle: outlet high limit',
     357: 'Abnormal Recycle: fault DHW sensor',
     358: 'Abnormal Recycle: DHW high limit',
     359: 'Abnormal Recycle: fault inlet sensor',
     360: 'Abnormal Recycle: Check Parameters Failed',
     361: 'Internal error: No factory parameters were detected in control',
     362: 'Internal error: PID iteration frequency was invalid',
     363: 'Internal error: Demand-Rate interval time was invalid',
     364: 'Internal error: Factory calibration parameter for modulation was invalid',
     365: 'Internal error: CH PID P-scaler was invalid',
     366: 'Internal error: CH PID I-scaler was invalid',
     367: 'Internal error: CH PID D-scaler was invalid',
     368: 'Internal error: DHW PID P-scaler was invalid',
     369: 'Internal error: DHW PID I-scaler was invalid',
     370: 'Internal error: DHW PID D-scaler was invalid',
     371: 'Internal error: Lead Lag master PID P-scaler was invalid',
     372: 'Internal error: Lead Lag master PID I-scaler was invalid',
     373: 'Internal error: Lead Lag master PID D-scaler was invalid',
     374: 'Abnormal Recycle: Hardware flame bias high',
     375: 'Abnormal Recycle: Hardware flame bias low',
     376: 'Abnormal Recycle: Hardware flame bias delta high',
     377: 'Abnormal Recycle: Hardware flame bias delta low',
     378: 'Abnormal Recycle: Hardware flame bias dynamic high',
     379: 'Abnormal Recycle: Hardware flame bias dynamic low',
     380: 'Abnormal Recycle: Fan Speed Not Proven',
     381: 'Abnormal Recycle: Fan Speed Range Low',
     382: 'Abnormal Recycle: Fan Speed Range High',
     389: 'Abnormal Recycle: AC power frequency Mismatch',
     451: 'Circulator control was invalid',
     452: 'Circulator P-gain was invalid',
     453: 'Circulator I-gain was invalid',
     454: 'Circulator temperature was invalid',
     455: 'Circulator outlet temperature was invalid',
     456: 'Circulator inlet temperature was invalid',
     457: 'Circulator outdoor temperature was invalid',
     458: 'Circulator sensor choice was invalid',
     459: 'Circulator PID setpoint was invalid',
     460: 'LCI lost in run',
     461: 'Abnormal Recycle: Demand lost in run from application',
     462: 'Abnormal Recycle: Demand lost in run due to high limit',
     463: 'Abnormal Recycle: Demand lost in run due to no flame',
     464: 'LCI lost in Combustion Pressure Establishing Period',
     465: 'LCI lost in Combustion Pressure Stabilization Period',
     467: 'Internal error: EEPROM write was attempted before EEPROM was initialized',
     468: 'Internal error: EEPROM cycle count address was invalid',
     469: 'Internal error: EEPROM days count address was invalid',
     470: 'Internal error: EEPROM hours count address was invalid',
     471: 'Internal error: Lockout record EEPROM index was invalid',
     472: 'Internal error: Request to write PM status was invalid',
     473: 'Internal error: PM parameter address was invalid',
     474: 'Internal error: PM safety parameter address was invalid',
     475: 'Internal error: Invalid record in lockout history was removed',
     476: 'Internal error: EEPROM write buffer was full',
     477: 'Internal error: Data too large was not written to EEPROM',
     478: 'Internal error: Safety key bit 0 was incorrect',
     479: 'Internal error: Safety key bit 1 was incorrect',
     480: 'Internal error: Safety key bit 2 was incorrect',
     481: 'Internal error: Safety key bit 3 was incorrect',
     482: 'Internal error: Safety key bit 4 was incorrect',
     483: 'Internal error: Safety key bit 5 was incorrect',
     484: 'Internal error: Safety key bit 6 was incorrect',
     485: 'Internal error: Safety key bit 7 was incorrect',
     486: 'Internal error: Safety key bit 8 was incorrect',
     487: 'Internal error: Safety key bit 9 was incorrect',
     488: 'Internal error: Safety key bit 10 was incorrect',
     489: 'Internal error: Safety key bit 11 was incorrect',
     490: 'Internal error: Safety key bit 12 was incorrect',
     491: 'Internal error: Safety key bit 13 was incorrect',
     492: 'Internal error: Safety key bit 14 was incorrect',
     493: 'Internal error: Safety key bit 15 was incorrect',
     494: 'Internal error: Safety relay timeout',
     495: 'Internal error: Safety relay commanded off',
     496: 'Internal error: Unknown safety error occurred',
     497: 'Internal error: Safety timer was corrupt',
     498: 'Internal error: Safety timer was expired',
     499: 'Internal error: Safety timings',
     500: 'Internal error: Safety shutdown',
     502: 'Mix setpoint was invalid',
     503: 'Mix time of day setpoint was invalid',
     504: 'Mix outdoor temperature was invalid',
     505: 'Mix ODR time of day setpoint was invalid',
     506: 'Mix ODR time of day setpoint exceeds normal setpoint',
     507: 'Mix ODR max outdoor temperature was invalid',
     508: 'Mix ODR min outdoor temperature was invalid',
     509: 'Mix ODR low water temperature was invalid',
     510: 'Mix ODR outdoor temperature range was invalid',
     511: 'Mix ODR water temperature range was invalid',
     512: 'Mix demand switch was invalid',
     513: 'Mix ON hysteresis was invalid',
     514: 'Mix OFF hysteresis was invalid',
     515: 'Mix ODR min water temperature was invalid',
     516: 'Mix hysteresis step time was invalid',
     517: 'Mix P-gain was invalid',
     518: 'Mix I-gain was invalid',
     519: 'Mix D-gain was invalid',
     520: 'Mix control was suspended due to fault',
     521: 'Mix S10 (J10-7) temperature was invalid',
     522: 'Mix outlet temperature was invalid',
     523: 'Mix inlet temperature was invalid',
     524: 'Mix S5 (J8-11) temperature was invalid',
     525: 'Mix modulation sensor type was invalid',
     526: 'Mix ODR min water temperature setpoint was invalid',
     527: 'Mix circulator sensor was invalid',
     528: 'Mix flow control was invalid',
     529: 'Mix temperature was invalid',
     530: 'Mix sensor was invalid',
     531: 'Mix PID setpoint was invalid',
     532: 'STAT may not be a Mix demand source when Remote Stat is enabled',
     540: 'Delta T inlet/outlet enable was invalid',
     541: 'Delta T exchanger/outlet enable was invalid',
     542: 'Delta T inlet/exchanger enable was invalid',
     543: 'Delta T inlet/outlet degrees was out of range',
     544: 'Delta T exchanger/outlet degrees was out of range',
     545: 'Delta T inlet/exchanger degrees was out of range',
     546: 'Delta T response was invalid',
     547: 'Delta T inversion limit response was invalid',
     548: 'Delta T rate limit enable was invalid',
     549: 'Delta T exchanger/outlet wasn\'t allowed due to stack limit setting',
     550: 'Delta T inlet/outlet limit was exceeded',
     551: 'Delta T exchanger/outlet limit was exceeded',
     552: 'Delta T inlet/exchanger limit was exceeded',
     553: 'Inlet/outlet inversion occurred',
     554: 'Exchanger/outlet inversion occurred',
     555: 'Inlet/exchanger inversion occurred',
     556: 'Delta T exchanger/outlet wasn\'t allowed due to stack connector setting',
     557: 'Delta T inlet/exchanger wasn\'t allowed due to stack limit setting',
     558: 'Delta T inlet/exchanger wasn\'t allowed due to stack connector setting',
     559: 'Delta T delay was not configured for recycle response',
     560: 'Outlet T-rise enable was invalid',
     561: 'Heat exchanger T-rise enable was invalid',
     562: 'T-rise degrees was out of range',
     563: 'T-rise response was invalid',
     564: 'Outlet T-rise limit was exceeded',
     565: 'Heat exchanger T-rise limit was exceeded',
     566: 'Heat exchanger T-rise wasn\'t allowed due to stack limit setting',
     567: 'Heat exchanger T-rise wasn\'t allowed due to stack connector setting',
     568: 'Outlet T-rise wasn\'t allowed due to outlet connector setting',
     569: 'T-rise delay was not configured for recycle response',
     570: 'Heat exchanger high limit setpoint was out of range',
     571: 'Heat exchanger high limit response was invalid',
     572: 'Heat exchanger high limit was exceeded',
     573: 'Heat exchanger high limit wasn\'t allowed due to stack limit setting',
     574: 'Heat exchanger high limit wasn\'t allowed due to stack connector setting',
     575: 'Heat exchanger high limit delay was not configured for recycle response',
     576: 'CH pump output was invalid',
     577: 'DHW pump output was invalid',
     578: 'Boiler pump output was invalid',
     579: 'Auxiliary pump output was invalid',
     580: 'System pump output was invalid',
     581: 'Mix pump output was invalid',
     590: 'DHW plate preheat setpoint was invalid',
     591: 'DHW plate preheat ON hysteresis was invalid',
     592: 'DHW plate preheat OFF hysteresis was invalid',
     593: 'Tap detect degrees was out of range',
     594: 'Tap detect ON hysteresis was invalid',
     595: 'Inlet - DHW tap stop degrees was out of range',
     596: 'Outlet - Inlet tap stop degrees was out of range',
     597: 'DHW tap detect on threshold was invalid',
     598: 'DHW plate preheat detect on threshold was invalid',
     599: 'DHW plate preheat detect off threshold was invalid',
     600: 'Delta T inlet temperature was invalid',
     601: 'Delta T outlet temperature was invalid',
     602: 'Delta T exchanger temperature was invalid',
     603: 'CH ODR boost max offpoint temperature was invalid',
     604: 'CH ODR boost max offpoint temperature was too low',
     605: 'Lead Lag ODR boost max offpoint temperature was invalid',
     606: 'Lead Lag ODR boost max offpoint temperature was too low',
     607: 'Mix ODR boost max offpoint temperature was invalid',
     608: 'Mix ODR boost max offpoint temperature was too low',
     609: 'Time to rotate lead boiler to next firing slave',
     610: 'Time to rotate lead boiler to next available slave',
     611: 'Time to rotate lead boiler to first firing slave in order',
     612: 'Time to rotate lead boiler to lowest running slave',
     613: 'Lead boiler was rotated based on new firing sequence order',
     614: 'Lead boiler was rotated based on measured run time',
     615: 'Parameter PCB was switched to backup',
     616: 'Range PCB was switched to backup'}


